# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tobias Kürschner
email:
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Dr. Tobias Kürschner's professional website. Tobias Kürschner is an ecologist and data scientist specializing in individual/agent-based modeling, wildlife disease ecology, and advanced data analysis. With a passion for understanding wildlife disease dynamics, biodiversity, and conservation, Tobias Kürschner leverages statistical modeling, machine learning, and spatial analysis to provide insights into ecological systems. Discover more about his research, projects, and publications in disease ecology, ecological modeling, and data-driven solutions for conservation.
Keywords:
Ecologist, Wildlife Disease Ecology, Individual-Based Modeling, Agent-Based Modeling, Data Science in Ecology, Disease Ecology Research, Conservation Data Science, Wildlife Modeling, Biodiversity Analysis, Ecological Modeling, Statistical Ecology, Agent-Based Modeling in Wildlife, Computational Ecology, Ecosystem Modeling, Population Dynamics Modeling, Zoonotic Disease Ecology, Infectious Disease Modeling in Wildlife, Predictive Modeling for Ecosystems, Disease Transmission in Wildlife Populations, Statistical Analysis in Ecology, Behavioral Ecology Modeling
github_username: tkuerschner
minimal_mistakes_skin: "dark"
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dr. Tobias Kürschner"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I am a ecologist with focus on individual-based models and disease ecology."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tobias.kuerschner@gmail.com"
    - label: "Researchgate"
      icon: ""
      url: "https://www.researchgate.net/profile/Tobias-Kuerschner"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tkuerschner"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tobias.kuerschner@gmail.com"
    - label: "Researchgate"
      icon: ""
      url: "https://www.researchgate.net/profile/Tobias-Kuerschner"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tkuerschner"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
